apiVersion: v2
name: music-assistant
description: A Helm chart for Kubernetes
maintainers:
  - name: toanju
    email: toanju@users.noreply.github.com
    url: https://github.com/toanju/
home: https://github.com/toanju/helm-charts
sources:
  - https://github.com/toanju/helm-charts
  - https://github.com/music-assistant/server

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.7.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# https://github.com/music-assistant/server/releases
appVersion: "2.7.8"
