apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lldap.fullname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
data:
  lldap_config.toml: |
    {{- include "lldap.configToToml" . | nindent 4 }}
