{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "lldap.fullname" . }}-pvc
spec:
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}
{{- if .Values.persistence.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
{{- else }}
  storageClassName: ""
{{- end }}
{{- if .Values.persistence.volumeMode }}
  volumeMode: "{{ .Values.persistence.volumeMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- if .Values.persistence.selector }}
  selector:
  {{- toYaml .Values.persistence.selector | nindent 4 }}
{{- end -}}
{{- if .Values.persistence.volumeName }}
  volumeName: "{{ .Values.persistence.volumeName }}"
{{- end -}}
{{- end -}}
{{- end -}}
